// autogenerated by /Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/build-books.ts. Do not edit!

export type Book = typeof books[number]
export const getBooks = () => books
export const getBook = (slug: string) => books.find(book => book.slug === slug)

const books = [
  {
    "file": "/Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/content/books/00001-never-split-the-difference/index.mdx",
    "content": "\nPeccato per la traduzione del titolo in italiano,\nche è un titolo talmente spudaratamente \"clickbait\" che l'ho evitato per anni nonostante\nin molti mi abbiano consigliato di leggerlo. E alla fine l'ho letto in inglese.\n\n**Never Split the Difference** parla di negoziazione e di come applicare tecniche psicologiche sviluppate da esperti\nnegoziatori dell'FBI nella vita reale, sia lavorativa che privata.\n\nLa cosa più interessante che ho imparato da questo\nlibro è quello che l'autore chiama **active listening**: molto spesso nelle conversazioni cerchiamo\ndi attirare l'attenzione\nsu noi stessi e sul nostro punto di vista,\ntanto che spesso nemmeno capiamo quello che vogliono dire gli altri.\nL'ascolto attivo invece prevede di focalizzarsi sull'interlocutore e cercare di capire non solo quello che dice,\nma quello che veramente pensa.\n",
    "slug": "never-split-the-difference-voss",
    "frontMatter": {
      "author": "Chris Voss",
      "links": {
        "it": "https://amzn.to/3HWdshA",
        "en": "https://amzn.to/3nhspD9"
      },
      "title": "Never Split the Difference: Negotiating as if Your Life Depended on It",
      "readTime": 1,
      "href": "/books/never-split-the-difference-voss",
      "image": "/books/00001-never-split-the-difference/never.jpg",
      "imagePath": "/books/00001-never-split-the-difference"
    }
  },
  {
    "file": "/Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/content/books/00002-influence/index.mdx",
    "content": "\nIn che modo prendiamo le decisioni? Secondo Cialdini, ogni giorno siamo sommersi di piccole e grandi decisioni da prendere,\ne il nostro cervello non ha abbastanza energie mentali per soffermarsi su tutte.\nPer questo motivo, molto spesso, adottiamo delle scorciatoie decisionali (automatismi) che ci permettono di fare una\nscelta senza doverci necessariamente pensare.\nQueste scorciatorie possono essere usate (come nel caso del marketing) per influenzare le nostre scelte in vari ambiti\ndella nostra vita senza necessariamente che noi siamo consci del fatto di essere influenzati.\n\nIn questo libro sono presentati i 6 princidi scoperti da Cialdini e dal suo gruppo di ricerca secondo cui\nfacciamo le nostre scelte quotidiane. Secondo l'autore questi principi sono universali ed usati\n(chi più, chi meno) da tutti gli esseri umani.\nDopo aver letto questo libro mi sono reos conto di molti comportamenti automatici che\ngiornamente adotto senza nemmeno accorgermi!\n",
    "slug": "influence-cialdini",
    "frontMatter": {
      "author": "Robert Cialdini",
      "links": {
        "it": "https://amzn.to/3r5Venb",
        "en": "https://amzn.to/3GaLdeN"
      },
      "title": "Influence: The Psychology of Persuasion",
      "readTime": 1,
      "href": "/books/influence-cialdini",
      "image": "/books/00002-influence/influence.jpg",
      "imagePath": "/books/00002-influence"
    }
  },
  {
    "file": "/Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/content/books/00003-rich-dad-poor-dad/index.mdx",
    "content": "\nHo scoperto essere un classico che mi era sfuggito fino al Novembre scorso. Ammetto di non averne mai sentito\nparlare prima anche se forse avrei dovuto farlo.\n\n**Padre Ricco Padre Povero** parla di finanza personale e di come è imporatante avere la\ngiusta mentalità ed un piano per raggiongere la _ricchezza_ o indipendenza economica,\nche per l'autore non si tratta di guadagnare un milione, 10 milioni o 100 milioni di € ma di\nriuscire ad ottenere un flusso di cassa costante tramite investimenti che ci permette di fare in\nmodo che i nostri soldi lavorino per noi.\n\nMolti spunti sono super interessanti, e sicuramente è uno dei libro che rileggerò nel 2022 per approfondirlo meglio.\n",
    "slug": "influence-cialdini",
    "frontMatter": {
      "author": "Robert Kiyosaki",
      "links": {
        "it": "https://amzn.to/3qhfkvm",
        "en": "https://amzn.to/3GcaBRk"
      },
      "title": "Rich Dad Pood Dad",
      "readTime": 1,
      "href": "/books/influence-cialdini",
      "image": "/books/00003-rich-dad-poor-dad/rich-dad-poor-dad.jpg",
      "imagePath": "/books/00003-rich-dad-poor-dad"
    }
  },
  {
    "file": "/Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/content/books/00004-wim-hof-method/index.mdx",
    "content": "\nWim Hof, anche noto come **the Ice Man**, è un personaggio molto interessante che ha diffuso un metodo di miglioramento\ndel corpo e dello spirito tramite il freddo.\n\nIl tutto è partito un po' per caso grazie al mio interesse per le doccie fredde\ne la lettura qualche mese fa di alcuni articoli sui benefici della doccia fredda.\nParlandone in giro mi è stato suggerito di seguire Wim Hof, che ha trasformato la propria passione\ned interesse verso il freddo in un metodo che insegna a miglioni di persone nel mondo.\n\nWim è capace di controllare il proprio metabolismo fino a riscaldare a comando parti del proprio corpo e\nsopprimere reazioni del proprio corpo ad alcune sostanze nocive.\nQuesta capacità è dimostrata in diversi esperimenti scientifici a cui lui e i suoi studenti si sono sottoposti.\nMa Wim crede nel fatto che queste capacità sono innate in tutte le persone e devono semplicemente essere sbloccate.\n\nNel libro Wim racconta la sua vita e il suo metodo, nato da anni di sperimentazioni con il freddo,\nche consiste essenzialmente nella graduale esposizione\nal freddo (a partire dalle doccie fredde fino ai bagni a 0 gradi) e in tecniche di respirazione.\nDa quando lo conosco cerco ogni giorno di fare una doccia (almeno parzialmente) fredda.\nD'estate era molto più facile, questo inverno inizia ad essere complicato ma almeno una 20 di secondi\nad ogni doccia che faccio li dedico all'acqua completamente fredda. E i benefici si fanno decisamente vedere.\n\nHo anche provate le tecniche di respirazione che Wim propone, e devo dire che, almeno per me, funzionano.\n\nNel prossimo futuro, pandemia permettendo, mi piacerebbe partecipare ad uno dei workshop che Wim organizza,\ne sto cercando qualche pazzo che voglia venire com me! Nel caso, se ti interessa, puoi scrivermi nei commenti.\n\nSe siete vagamente interessati alla cosa ecco un documentario super figo che spiega meglio di me il processo.\n\n<YouTube videoId=\"8cvhwquPqJ0\" />\n",
    "slug": "wim-hof-method",
    "frontMatter": {
      "author": "Wim Hof",
      "links": {
        "en": "https://amzn.to/3HWpurh"
      },
      "title": "The Wim Hof Method",
      "readTime": 2,
      "href": "/books/wim-hof-method",
      "image": "/books/00004-wim-hof-method/wim-hof.jpg",
      "imagePath": "/books/00004-wim-hof-method"
    }
  },
  {
    "file": "/Users/ludusrusso/develop/github.com/ludusrusso/www.ludusrusso.dev/content/books/00005-how-to-win-friends/index.mdx",
    "content": "\nUltimo libro letto nel 2021, proprio al pelo del 2022 (tanto che ero indeciso di metterlo qui dentro).\nAnche questo un mega classico che ho scoperto troppo tardi, che essenzialmente parla di quali sono gli\natteggiamenti da tenere e i modi di fare\nper migliorare le nostre relazioni con gli altri e creare legami i amicizia duraturi nel tempo,\nche possano portare benefici ad entrambi. Molte idee sono simili a quelle presentate in\nNever Split the Difference di Chris Voss, ma in questo caso il focus non è quello di negoziare\nma di creare relazioni con le altre persone.\n\nUn libro che sicuramente rileggerò per ottenere il massimo da quello che dice,\nma che già dalla prima lettura sta influenzando il mio modo di pensare e di relazionarmi con le altre persone.\n",
    "slug": "how-to-win-friends-and-influcence-people-carnagie",
    "frontMatter": {
      "author": "Dale Carnegie",
      "links": {
        "en": "https://amzn.to/3r8dEUs",
        "it": "https://amzn.to/32ZDXUR"
      },
      "title": "How to Win Friends and Influence People",
      "readTime": 1,
      "href": "/books/how-to-win-friends-and-influcence-people-carnagie",
      "image": "/books/00005-how-to-win-friends/friends.jpg",
      "imagePath": "/books/00005-how-to-win-friends"
    }
  }
]