export type EpisodeParticipant = {
  id: string;
  name: string;
  email: string;
  github: string | null;
  bio: string;
  avatar: string | null;
  twitter?: string | null;
  linkedin?: string | null;
  updatedAt: string;
};

export type Episode = {
  id: string;
  title: string;
  description: string;
  body: string;
  resources: string | null;
  image: string | null;
  hostId: string;
  youtube: string | null;
  twitch: string;
  category: string;
  scheduledTime: Date;
  host: EpisodeParticipant;
  guests: { guest: EpisodeParticipant }[];
};

export function episodes(): Episode[] {
  return [
    {
      id: "cl1xs4jmb006009l0te2teq9y",
      title: "Random dev: riprendiamo a sviluppare **Kannon** con Go 1.18",
      description:
        "Dopo un anno che non ci faccio sviluppo, riprendiamo in mano il mio progetto Open Source Kannon 📧",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: null,
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-04-13T16:20:53.459Z",
      updatedAt: "2022-04-13T16:23:39.749Z",
      scheduledTime: "2022-04-13T19:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 25,
          episodeId: "cl1xs4jmb006009l0te2teq9y",
          guestId: "cky1gonti0028n0xqml7gmfcd",
          guest: {
            id: "cky1gonti0028n0xqml7gmfcd",
            name: "Davide Imola",
            email: "davide.imola@icloud.com",
            github: "davideimola",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "davideimola",
            linkedin: "davideimola",
            createdAt: "2022-01-05T11:32:51.990Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "ckzsyjywr003709lcsf83hf8x",
      title: "Stanno per arrivare i *Generics* in *Golang* 🚀🚀🚀",
      description:
        "I generics in Go sono quasi realtà, tra pochi giorni verrà rilasciata la release stabile di Go 1.18! Ma io e Jaga vogliamo provarli prima del rilascio!",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: null,
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-02-18T22:02:35.259Z",
      updatedAt: "2022-02-18T22:04:52.797Z",
      scheduledTime: "2022-02-20T09:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 24,
          episodeId: "ckzsyjywr003709lcsf83hf8x",
          guestId: "ckym03upx003309l9qokud4km",
          guest: {
            id: "ckym03upx003309l9qokud4km",
            name: "Jaga Santagostino",
            email: "jagasantagostino@gmail.com",
            github: "kandros",
            bio: "Frontend Architectures Consultant",
            avatar: null,
            twitter: "kandros5591",
            linkedin: null,
            createdAt: "2022-01-19T20:31:56.997Z",
            updatedAt: "2022-01-19T20:31:56.998Z",
          },
        },
      ],
    },
    {
      id: "ckzfaszc0005509l44qmw06c6",
      title:
        "Sviluppiamo tool per gestire i nostri stream con *graphql*, *golang* e *kubernetes* - parte 2",
      description:
        "Settimana scorsa siamo riusciti ad avere una demo quasi funzionante, questa volta andiamo avanti per cercare di collegare e deployare il tutto",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "nTjpCDojeCQ",
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-02-09T08:36:44.640Z",
      updatedAt: "2022-02-14T14:03:47.541Z",
      scheduledTime: "2022-02-13T09:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 23,
          episodeId: "ckzfaszc0005509l44qmw06c6",
          guestId: "ckym03upx003309l9qokud4km",
          guest: {
            id: "ckym03upx003309l9qokud4km",
            name: "Jaga Santagostino",
            email: "jagasantagostino@gmail.com",
            github: "kandros",
            bio: "Frontend Architectures Consultant",
            avatar: null,
            twitter: "kandros5591",
            linkedin: null,
            createdAt: "2022-01-19T20:31:56.997Z",
            updatedAt: "2022-01-19T20:31:56.998Z",
          },
        },
      ],
    },
    {
      id: "ckz85gp0y005309mbr4sgiags",
      title:
        "Sviluppiamo tool per gestire i nostri stream con *graphql*, *golang* e *kubernetes*",
      description:
        "Ci vogliamo male, quindi vogliamo provare a sviluppare il nostro streamyard fatto con casa in golang e graphql!",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "A3m-Z_ULfaY",
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-02-04T08:32:50.098Z",
      updatedAt: "2022-02-06T14:06:55.008Z",
      scheduledTime: "2022-02-06T09:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 22,
          episodeId: "ckz85gp0y005309mbr4sgiags",
          guestId: "ckym03upx003309l9qokud4km",
          guest: {
            id: "ckym03upx003309l9qokud4km",
            name: "Jaga Santagostino",
            email: "jagasantagostino@gmail.com",
            github: "kandros",
            bio: "Frontend Architectures Consultant",
            avatar: null,
            twitter: "kandros5591",
            linkedin: null,
            createdAt: "2022-01-19T20:31:56.997Z",
            updatedAt: "2022-01-19T20:31:56.998Z",
          },
        },
      ],
    },
    {
      id: "ckyyafgrp007209k5xweh0ars",
      title: "Setup di un ambiente di stream con *twitch*, *obs* e *nextjs*",
      description:
        "Come ho configurato il mio ambiente di livestreaming? Cosa possiamo migliorare? Aiutiamo Jaga a costruirsene uno per se!",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "51gvlL_Qt_E",
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-01-28T10:54:09.061Z",
      updatedAt: "2022-01-30T13:01:25.219Z",
      scheduledTime: "2022-01-30T09:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 21,
          episodeId: "ckyyafgrp007209k5xweh0ars",
          guestId: "ckym03upx003309l9qokud4km",
          guest: {
            id: "ckym03upx003309l9qokud4km",
            name: "Jaga Santagostino",
            email: "jagasantagostino@gmail.com",
            github: "kandros",
            bio: "Frontend Architectures Consultant",
            avatar: null,
            twitter: "kandros5591",
            linkedin: null,
            createdAt: "2022-01-19T20:31:56.997Z",
            updatedAt: "2022-01-19T20:31:56.998Z",
          },
        },
      ],
    },
    {
      id: "ckym073nt012109l97xfhcy9q",
      title: "Autenticazione con NextAuth",
      description:
        "Implementiamo l'autenticazione ad Hackability.dev con NextAuth",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "WgLRj_laCu8",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-19T20:34:28.553Z",
      updatedAt: "2022-01-28T13:44:10.392Z",
      scheduledTime: "2022-01-24T16:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 20,
          episodeId: "ckym073nt012109l97xfhcy9q",
          guestId: "ckxyt5cuj008409mkiuuiaepe",
          guest: {
            id: "ckxyt5cuj008409mkiuuiaepe",
            name: "Gerson Enriquez",
            email: "gersonenriquez94@gmail.com",
            github: "GersonEC",
            bio: "Frontend Developer",
            avatar: null,
            twitter: null,
            linkedin: null,
            createdAt: "2022-01-03T14:58:27.787Z",
            updatedAt: "2022-01-03T14:58:27.788Z",
          },
        },
      ],
    },
    {
      id: "ckym05sn9008109l92bafyh30",
      title: "Code Generator in GO",
      description:
        "Programmi che scrivono programmi? Implementiamo il nostro Code Generator in Go",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "iTMLCsAI038",
      twitch: "ludusrusso",
      category: "livefun",
      createdAt: "2022-01-19T20:33:27.621Z",
      updatedAt: "2022-01-28T13:44:10.392Z",
      scheduledTime: "2022-01-23T09:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 19,
          episodeId: "ckym05sn9008109l92bafyh30",
          guestId: "ckym03upx003309l9qokud4km",
          guest: {
            id: "ckym03upx003309l9qokud4km",
            name: "Jaga Santagostino",
            email: "jagasantagostino@gmail.com",
            github: "kandros",
            bio: "Frontend Architectures Consultant",
            avatar: null,
            twitter: "kandros5591",
            linkedin: null,
            createdAt: "2022-01-19T20:31:56.997Z",
            updatedAt: "2022-01-19T20:31:56.998Z",
          },
        },
      ],
    },
    {
      id: "ckybj55z10061xr5cxqyx05ww",
      title: "La Gilda dei DEVulgatori",
      description:
        "Un bel po' di Dev fighi (e poi io) a fare caciara su twitch tutti insieme per una live che promette bene :D",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "njAGYQ59I6c",
      twitch: "continuousdelivery",
      category: "livefun",
      createdAt: "2022-01-12T12:39:23.005Z",
      updatedAt: "2022-01-18T09:02:43.506Z",
      scheduledTime: "2022-01-13T17:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [],
    },
    {
      id: "ckxyt6jzt015009mkko8ehx5h",
      title: "Ritorniamo a NextJS",
      description:
        "Blitzjs è ufficialmente un progetto che subirà pensanti modifiche. Abbiamo quindi deciso di ritornare a NextJS sfruttando le nozioni che abbiamo imparato con Blitz!",
      body: "",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "vZyGX8oMqQs",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-03T14:59:23.705Z",
      updatedAt: "2022-01-20T09:20:46.890Z",
      scheduledTime: "2022-01-05T17:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 1,
          episodeId: "ckxyt6jzt015009mkko8ehx5h",
          guestId: "ckxyt5cuj008409mkiuuiaepe",
          guest: {
            id: "ckxyt5cuj008409mkiuuiaepe",
            name: "Gerson Enriquez",
            email: "gersonenriquez94@gmail.com",
            github: "GersonEC",
            bio: "Frontend Developer",
            avatar: null,
            twitter: null,
            linkedin: null,
            createdAt: "2022-01-03T14:58:27.787Z",
            updatedAt: "2022-01-03T14:58:27.788Z",
          },
        },
      ],
    },
    {
      id: "cky1gop5c0098n0xq3lnyqywx",
      title: "Creare un form complesso per Hackability con react final-form",
      description:
        "Hackability space prende finalmente forma. Abbiamo la lista dei progetti ma dobbiamo dare la possibilità agli utenti di crearli e aggiornarli.",
      body: "\nHackability space prende finalmente forma. Abbiamo la lista dei progetti ma dobbiamo dare la possibilità agli utenti di crearli e aggiornarli.\n\n- [Tailwind](https://tailwindui.com/)\n- [Emotions](https://emotion.sh/)\n- [Final Form](https://final-form.org/react)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "WWFb9A-Uw04",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:53.712Z",
      updatedAt: "2022-01-20T09:20:46.890Z",
      scheduledTime: "2021-12-22T17:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 10,
          episodeId: "cky1gop5c0098n0xq3lnyqywx",
          guestId: "ckxyt5cuj008409mkiuuiaepe",
          guest: {
            id: "ckxyt5cuj008409mkiuuiaepe",
            name: "Gerson Enriquez",
            email: "gersonenriquez94@gmail.com",
            github: "GersonEC",
            bio: "Frontend Developer",
            avatar: null,
            twitter: null,
            linkedin: null,
            createdAt: "2022-01-03T14:58:27.787Z",
            updatedAt: "2022-01-03T14:58:27.788Z",
          },
        },
      ],
    },
    {
      id: "cky1gop5f0100n0xqv2yjhpb6",
      title:
        "Frontend design con TailwindCSS e EmotionsCSS per hackability.dev",
      description:
        "Insieme a Gerson facciamo un po' frontend usando tailiwind e emotions",
      body: "\nHackability space prende forma, sperando sia quella definitiva.\nIn questa puntata abbiamo lavorato con Gerson per stilizzare la homepage del sito.\n\n- [Tailwind](https://tailwindui.com/)\n- [Emotions](https://emotion.sh/)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "U4mADicouhw",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:53.715Z",
      updatedAt: "2022-01-05T11:32:53.716Z",
      scheduledTime: "2021-12-15T17:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 7,
          episodeId: "cky1gop5f0100n0xqv2yjhpb6",
          guestId: "ckxyt5cuj008409mkiuuiaepe",
          guest: {
            id: "ckxyt5cuj008409mkiuuiaepe",
            name: "Gerson Enriquez",
            email: "gersonenriquez94@gmail.com",
            github: "GersonEC",
            bio: "Frontend Developer",
            avatar: null,
            twitter: null,
            linkedin: null,
            createdAt: "2022-01-03T14:58:27.787Z",
            updatedAt: "2022-01-03T14:58:27.788Z",
          },
        },
      ],
    },
    {
      id: "cky1good50066n0xqlbrcbkfd",
      title: "Migiramo su Blitz.js",
      description:
        "Finalmente riprendiamo a lavorare su `hackability.dev`, questa volta con Gerson e su Twitch! Abbiamo lascito per mesi il progetto in pending ma finalmente siamo pronti a riprenderlo usando Blitz e Prisma",
      body: "\nFinalmente riprendiamo a lavorare su `hackability.dev`, questa volta con Gerson e su Twitch!\nVogliamo spostare l'intero progetto su Blitz.js e ritornare a gestire il database con Prisma!\n\n- [Blitz.js](https://blitzjs.com/)\n- [Prisma](https://www.prisma.io/)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "QMrHR-OujWk",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:52.697Z",
      updatedAt: "2022-01-05T11:32:52.698Z",
      scheduledTime: "2021-12-09T17:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 2,
          episodeId: "cky1good50066n0xqlbrcbkfd",
          guestId: "ckxyt5cuj008409mkiuuiaepe",
          guest: {
            id: "ckxyt5cuj008409mkiuuiaepe",
            name: "Gerson Enriquez",
            email: "gersonenriquez94@gmail.com",
            github: "GersonEC",
            bio: "Frontend Developer",
            avatar: null,
            twitter: null,
            linkedin: null,
            createdAt: "2022-01-03T14:58:27.787Z",
            updatedAt: "2022-01-03T14:58:27.788Z",
          },
        },
      ],
    },
    {
      id: "cky1goonp0069n0xqyoqoayqh",
      title: "Ancora CI Database e GitOps",
      description:
        "La volta scorsa abbiamo lasciato in sospeso alcuni pezzi di CI e migrazione dei database. Questa volta cercheremo di risolvere i problemi per avere una CI finalmente perfetta",
      body: "\nRitorniamo a lavorare con Davide e Lorenzo sulla CI e sul Database per chiudere quello\nlasciato in sospero la volta precedente.\nParleremo quindi di github action e come gestire le migrazioni con dbmate!\n\n- [Dbmate](https://github.com/amacneil/dbmate)\n- [GitHub Actions](https://github.com/features/actions)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "37B0_m5UbLs",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:53.077Z",
      updatedAt: "2022-01-05T11:32:53.078Z",
      scheduledTime: "2021-03-20T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 6,
          episodeId: "cky1goonp0069n0xqyoqoayqh",
          guestId: "cky1gonau0014n0xq0e1k3am7",
          guest: {
            id: "cky1gonau0014n0xq0e1k3am7",
            name: "Lorenzo Gallucci",
            email: "lgallucci@gmail.com",
            github: "log2",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "log_two",
            linkedin: "log2",
            createdAt: "2022-01-05T11:32:51.318Z",
            updatedAt: "2022-01-12T12:35:24.188Z",
          },
        },
        {
          id: 5,
          episodeId: "cky1goonp0069n0xqyoqoayqh",
          guestId: "cky1gonti0028n0xqml7gmfcd",
          guest: {
            id: "cky1gonti0028n0xqml7gmfcd",
            name: "Davide Imola",
            email: "davide.imola@icloud.com",
            github: "davideimola",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "davideimola",
            linkedin: "davideimola",
            createdAt: "2022-01-05T11:32:51.990Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "cky1gopgl0131n0xqippq7a1g",
      title: "CI Database e GitOps",
      description:
        "Ritorniamo a gestire la parte devops, e migriamo il database management da prisma ad un progetto interessante che ci semplifica tanto la vita",
      body: "\nRitorniamo a lavorare con Davide e Lorenzo sulla CI e sul Database.\nQuello che vorremmo fare è migrare la gestione del database da Prisma a **DBMate** e **PgTyped**,\ne trovare un modo semplice per gestire le imgrazioni del db tramite Kubernetes.\n\n- [Dbmate](https://github.com/amacneil/dbmate)\n- [PgTyped](https://github.com/adelsz/pgtyped)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "BW29Zqwqk_Q",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:54.117Z",
      updatedAt: "2022-01-05T11:32:54.117Z",
      scheduledTime: "2021-03-20T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 12,
          episodeId: "cky1gopgl0131n0xqippq7a1g",
          guestId: "cky1gonau0014n0xq0e1k3am7",
          guest: {
            id: "cky1gonau0014n0xq0e1k3am7",
            name: "Lorenzo Gallucci",
            email: "lgallucci@gmail.com",
            github: "log2",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "log_two",
            linkedin: "log2",
            createdAt: "2022-01-05T11:32:51.318Z",
            updatedAt: "2022-01-12T12:35:24.188Z",
          },
        },
        {
          id: 11,
          episodeId: "cky1gopgl0131n0xqippq7a1g",
          guestId: "cky1gonti0028n0xqml7gmfcd",
          guest: {
            id: "cky1gonti0028n0xqml7gmfcd",
            name: "Davide Imola",
            email: "davide.imola@icloud.com",
            github: "davideimola",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "davideimola",
            linkedin: "davideimola",
            createdAt: "2022-01-05T11:32:51.990Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "cky1goq480185n0xqg6j8qmqk",
      title: "Costruiamo il sito con Next.js e React",
      description:
        "Riprendiamo lo sviluppo del sito, questa volta insieme ad Alessandro e John nel mondo di React e Next.js",
      body: "\nAbbiamo una CI/CD funzionante, abbiamo iniziato a sviluppare delle API\ngraphql e predisposto tutto per il prerendering delle pagine.\nAdesso ci possiamo lanciare sul mondo dello sviluppo frontend insieme ad\nAlessandro e John.\n\n- [React](https://it.reactjs.org/)\n- [Next](https://nextjs.org/docs/api-routes/introduction)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "hZeASrVodzc",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:54.968Z",
      updatedAt: "2022-01-05T11:32:54.969Z",
      scheduledTime: "2021-03-06T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 15,
          episodeId: "cky1goq480185n0xqg6j8qmqk",
          guestId: "cky1gopff0126n0xq5l2d0u6w",
          guest: {
            id: "cky1gopff0126n0xq5l2d0u6w",
            name: "Alessandro Tornesello",
            email: "aletornesello@xxxx.xx",
            github: null,
            bio: "Frontend dev",
            avatar: null,
            twitter: null,
            linkedin: "alessandro-tornesello",
            createdAt: "2022-01-05T11:32:54.075Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
        {
          id: 16,
          episodeId: "cky1goq480185n0xqg6j8qmqk",
          guestId: "cky1gopfg0128n0xq59c7tor6",
          guest: {
            id: "cky1gopfg0128n0xq59c7tor6",
            name: "John Paul Du",
            email: "johnpaul@xxxx.xx",
            github: null,
            bio: "Frontend Dev",
            avatar: null,
            twitter: null,
            linkedin: "john-paul-du-0aa021144",
            createdAt: "2022-01-05T11:32:54.076Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "cky1gopjq0141n0xqr35x9ohj",
      title: "Costruiamo il sito con Next.js e React",
      description:
        "Siamo pronti a fare coding, insieme a Luca e Giandomenico ci lanciamo nel mondo di React e Next.js",
      body: "\nLa CI/CD funziona alla grande grazie a FluxCD e Github Actions,\nadesso ci possiamo lancaire nel mondo dello sviluppo vero e proprio\nusando alcune tecnologie molto fighe:\n\n- [React](https://it.reactjs.org/)\n- [Next](https://nextjs.org/docs/api-routes/introduction)\n\n## Cosa abbiamo fatto!\n\nSiamo partiti con l'idea di fare principalmente React e ci siamo lanciati sul mondo\nGraphql e backend iniziado ad implementare la struttura del db e creando un semplice\nset di api Graphql.\n\n- aggiunto un po' di modelli prisma per il database.\n- creato delle API Graphql tramite [apollo server micro](https://www.apollographql.com/docs/apollo-server/v1/servers/micro/)\n- reso l'index page di next generato staticamente grazie all'uso delle API\n- iniziato ad integrare [graphql code generator](https://graphql-code-generator.com/) per avere i file delle api tipizzati\n\n[![Demo](./demo.png)](https://space.k8s.hackability.dev/)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "aAKhxTsy_zw",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:54.230Z",
      updatedAt: "2022-01-05T11:32:54.231Z",
      scheduledTime: "2021-02-27T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 14,
          episodeId: "cky1gopjq0141n0xqr35x9ohj",
          guestId: "cky1gooc20062n0xq4y4o0a10",
          guest: {
            id: "cky1gooc20062n0xq4y4o0a10",
            name: "Giandomenico Riceputi",
            email: "giandomenicoriceputi@gmail.com",
            github: "GiandomenicoRiceputi",
            bio: "Frontend",
            avatar: null,
            twitter: "Giando_Riceputi",
            linkedin: "giandomenicoriceputi",
            createdAt: "2022-01-05T11:32:52.658Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
        {
          id: 13,
          episodeId: "cky1gopjq0141n0xqr35x9ohj",
          guestId: "cky1gop6d0104n0xq0amzixkn",
          guest: {
            id: "cky1gop6d0104n0xq0amzixkn",
            name: "Luca Brognara",
            email: "luca.brognara@comperio.it",
            github: null,
            bio: "Frontend dev",
            avatar:
              "https://res.cloudinary.com/ludusrusso/image/upload/c_crop,g_face/c_scale,w_200,h_200/v1641374825/ludusrusso.dev/participants/lucabrognara_sdnzix.jpg",
            twitter: "lucabrognara",
            linkedin: "lucabrognara",
            createdAt: "2022-01-05T11:32:53.749Z",
            updatedAt: "2022-01-05T11:32:53.750Z",
          },
        },
      ],
    },
    {
      id: "cky1gooc70064n0xqkt915h6r",
      title: "Implementiamo una CI/CD con Github Actions e Flux",
      description:
        "Prima di lanciarci nel coding, setuppiamo una CI/CD che ci agevolerà nel deployment dell'applicazione, con l'aiuto di Davide e Lorenzo!",
      body: '\nLa prima bozza di space Hackablity è online! Ma prima di iniziare lo sviluppo vero e proprio\ncon Next.js abbiamo bisogno di implementare un sistema di Continous Integration and Deployment\nfatto per bene.\n\nPer questo motivo, con l\'aiuto di Davide e Lorenzo, proviamo a setuppare una CI/CD usando le\nseguenti tecnologie:\n\n- [Github Actions](https://docs.github.com/en/actions)\n- [Flux 2](https://github.com/fluxcd/flux2)\n\n## Cosa abbiamo fatto!\n\nIl live è stato pieno di roba insegnata da Lorenzo, in particolare ci siamo concentrati\nsu due attività principali.\n\n### 1. Setup Flux2 su Kubernello\n\n[Flux2](https://fluxcd.io/) è un sistema che implementa GitOps per Kubernetes.\nIn parole povere, questo tool permette di gestire la configurazione del cluster e delle\napplicazioni che girano al suo interno sfruttando una repository git come unica\nsource of trouth. Questo ha enormi vantaggi rispetto al classico approccio CI/CD\n(per approfondire questo [video spiega molto bene l\'idea](https://www.youtube.com/watch?v=Mr_mbwsRDBI)),\n\nSeguendo [questa guida](https://toolkit.fluxcd.io/get-started/) abbiamo eseguito il\nbootstrap di Flux2 all\'interno di Kubernello, usando il comando:\n\n```bash\n$ flux bootstrap github --owner=hackability-dev --repository=env-space-hackabilty-dev --private=false\n\n### output\n\n► connecting to github.com\n✔ repository created\n✔ repository cloned\n✚ generating manifests\n✔ components manifests pushed\nI0220 15:22:20.434567   12847 request.go:655] Throttling request took 1.092061751s, request: GET:https://168.119.154.178:6443/apis/k3s.cattle.io/v1?timeout=32s\n► installing components in flux-system namespace\nnamespace/flux-system created\ncustomresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io created\ncustomresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io created\nserviceaccount/helm-controller created\nserviceaccount/kustomize-controller created\nserviceaccount/notification-controller created\nserviceaccount/source-controller created\nclusterrole.rbac.authorization.k8s.io/crd-controller-flux-system created\nclusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system created\nclusterrolebinding.rbac.authorization.k8s.io/crd-controller-flux-system created\nservice/notification-controller created\nservice/source-controller created\nservice/webhook-receiver created\ndeployment.apps/helm-controller created\ndeployment.apps/kustomize-controller created\ndeployment.apps/notification-controller created\ndeployment.apps/source-controller created\nnetworkpolicy.networking.k8s.io/allow-scraping created\nnetworkpolicy.networking.k8s.io/allow-webhooks created\nnetworkpolicy.networking.k8s.io/deny-ingress created\n◎ verifying installation\n✔ install completed\n► configuring deploy key\n✔ deploy key configured\n► generating sync manifests\n✔ sync manifests pushed\n► applying sync manifests\n◎ waiting for cluster sync\n✔ bootstrap finished\n```\n\nChe ha creato la repository [env-space-hackabilty-dev](https://github.com/hackability-dev/env-space-hackabilty-dev)\nsu cui poi abbiamo deployato le varie configurazioni di kubernetes e space hackability.\n\nAll\'interno del repo abbiamo copiato la cartella `k8s` contenente i file di configurazione\ndi kubernetes. In questo modo, ad ogni modifica di questi file Flux si occupa di\naggiornare lo stato di Kubernetes.\n\n**gitrepo-hackability-dev.yaml** che si occupa di informare Flux di monitorare la\nrepo git.\n\n```yaml\napiVersion: source.toolkit.fluxcd.io/v1beta1\nkind: GitRepository\nmetadata:\n  name: hackability-dev\n  namespace: flux-system\nspec:\n  gitImplementation: go-git\n  interval: 0m30s\n  ref:\n    branch: main\n  secretRef:\n    name: hackability-dev\n  timeout: 20s\n  url: ssh://git@github.com/hackability-dev/env-space-hackabilty-dev\n```\n\n### 2. Setup GitHub Action\n\nAbbiamo quindi configurato una [github actions](https://github.com/hackability-dev/space.hackability/blob/main/.github/workflows/ci.yml) che ci permette di deployare le immagini in modo automatico\nad ogni push che facciamo.\n\n```yaml\nname: CI\n\non:\n  push:\n    branches:\n      - "**"\n    tags:\n      - "v*"\njobs:\n  docker:\n    runs-on: ubuntu-latest\n    steps:\n      - name: Checkout\n        uses: actions/checkout@v2\n      - name: Docker meta\n        id: docker_meta\n        uses: crazy-max/ghaction-docker-meta@v1\n        with:\n          images: |\n            hackabilitydev/space-hackability\n          tag-sha: true\n          tag-semver: |\n            {{version}}\n            {{major}}.{{minor}}\n      - name: Set up Docker Buildx\n        uses: docker/setup-buildx-action@v1\n      - name: Login to DockerHub\n        uses: docker/login-action@v1\n        with:\n          username: ${{ secrets.DOCKERHUB_USERNAME }}\n          password: ${{ secrets.DOCKERHUB_TOKEN }}\n      - name: Build and push\n        id: docker_build\n        uses: docker/build-push-action@v2\n        with:\n          context: .\n          push: ${{ github.event_name != \'pull_request\' }}\n          tags: ${{ steps.docker_meta.outputs.tags }}\n          labels: ${{ steps.docker_meta.outputs.labels }}\n      - name: Image digest\n        run: echo ${{ steps.docker_build.outputs.digest }}\n```\n\nAd ogni push, questa action si occupa di compilare l\'immagine, pusharla all\'interno della repo [hackabilitydev/space-hackability](https://hub.docker.com/repository/docker/hackabilitydev/space-hackability)\nutilizzando il tag di git (se presente) e la sha del commit git. Alcuni esempi creati ieri:\n\n- [hackabilitydev/space-hackability:sha-44b50ad](https://hub.docker.com/layers/hackabilitydev/space-hackability/sha-44b50ad/images/sha256-9316402d65bddaf4258e2fc5c0c00721380f19808894c15813641223439d1888?context=repo) generato dal commit [44b50ad](https://github.com/hackability-dev/space.hackability/commit/44b50adaba9242ff12b4a0c55af3ccd643834784)\n- [hackabilitydev/space-hackability:0.1](https://hub.docker.com/layers/hackabilitydev/space-hackability/0.1/images/sha256-9316402d65bddaf4258e2fc5c0c00721380f19808894c15813641223439d1888?context=explore) generato dal tag [v0.1.0](https://github.com/hackability-dev/space.hackability/tree/v0.1.0)\n\n### 3. Flux Image Automation\n\nAbbiamo aggiunto un\'image automation sul repo flux. Questo soluzione consiste in 3 file yaml creati, e quindi\n3 oggetti kubernetes.\n\n[**space-hackability-image-repository.yaml**](https://github.com/hackability-dev/env-space-hackabilty-dev/blob/main/space-hackability-image-repository.yaml)\nche dice a flux di monitorare la repository **hackabilitydev/space-hackability** su cui deployamo le nuove immagini\n\n```yaml\n---\napiVersion: image.toolkit.fluxcd.io/v1alpha1\nkind: ImageRepository\nmetadata:\n  name: space-hackability\n  namespace: flux-system\nspec:\n  image: hackabilitydev/space-hackability\n  interval: 0m30s\n```\n\n[**image-policy.yaml**](https://github.com/hackability-dev/env-space-hackabilty-dev/blob/main/image-policy.yaml)\nche dice a Flux, in particolare, di monitorare la creazione di una nuova immagine con semver crescente\n\n```yaml\n---\napiVersion: image.toolkit.fluxcd.io/v1alpha1\nkind: ImagePolicy\nmetadata:\n  name: space-hackability\n  namespace: flux-system\nspec:\n  imageRepositoryRef:\n    name: space-hackability\n  policy:\n    semver:\n      range: ">=0.0.0"\n```\n\n[**image-update-automation.yaml**](https://github.com/hackability-dev/env-space-hackabilty-dev/blob/main/image-update-automation.yaml)\nche si attiva quando una nuova immagine viene trovata, ed esegue un push sulla repository aggiornando l\'immagine\ncontenuta all\'intero delle configurazioni kubernetes.\n\n```yaml\n---\napiVersion: image.toolkit.fluxcd.io/v1alpha1\nkind: ImageUpdateAutomation\nmetadata:\n  name: hackability-dev\n  namespace: flux-system\nspec:\n  checkout:\n    branch: main\n    gitRepositoryRef:\n      name: hackability-dev\n  commit:\n    authorEmail: fluxcdbot@users.noreply.github.com\n    authorName: fluxcdbot\n    messageTemplate: "[ci skip] update image"\n  interval: 0m30s\n```\n\nIl sistema riesce a capire cosa motificare grazie al commenti ` # {"$imagepolicy": "flux-system:space-hackability"}`\naggiunto all\'interno del file [**hackability-dev/deploy.yaml**](https://github.com/hackability-dev/env-space-hackabilty-dev/blob/main/hackability-dev/deploy.yaml).\n\n```yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  labels:\n    app: hackability\n  name: hackability\n  namespace: hackability-dev\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: hackability\n  strategy: {}\n  template:\n    metadata:\n      labels:\n        app: hackability\n    spec:\n      containers:\n        - image: hackabilitydev/space-hackability:0.1.1 # {"$imagepolicy": "flux-system:space-hackability"}\n          name: space-hackability\n          envFrom:\n            - secretRef:\n                name: db-access\n          ports:\n            - containerPort: 3000\n              name: http\n              protocol: TCP\n          resources:\n            limits:\n              cpu: 200m\n              memory: 128Mi\n```\n\nQuindi, ogni volta che creiamo un nuovo tag nella forma `v0.1.1` dentro la repo originale, github actions si\nattivano e creano una nuova immagine `hackabilitydev/space-hackability:0.1.1` che viene deployata su docker hub.\n\nA quel punto la image policy automation si accorge della nuova immagine e aggiorna il file deploy.yaml facendo\nun commit che aggiorna l\'immagine. Infine, Flux si accorge della modifica su github e aggiorna lo stato di Kubernetes.\n\nAbbiamo testato il tutto creado il tag [v0.1.1](https://github.com/hackability-dev/space.hackability/tree/v0.1.1)\nche ha generato l\'immagine `hackabilitydev/space-hackability:0.1.1` che è stata deployata correttamente.\n\n![Primo deploy con Flux](./demo.png)\n',
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "04NIQBy7j9Q",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:52.663Z",
      updatedAt: "2022-01-05T11:32:52.664Z",
      scheduledTime: "2021-02-20T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 4,
          episodeId: "cky1gooc70064n0xqkt915h6r",
          guestId: "cky1gonau0014n0xq0e1k3am7",
          guest: {
            id: "cky1gonau0014n0xq0e1k3am7",
            name: "Lorenzo Gallucci",
            email: "lgallucci@gmail.com",
            github: "log2",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "log_two",
            linkedin: "log2",
            createdAt: "2022-01-05T11:32:51.318Z",
            updatedAt: "2022-01-12T12:35:24.188Z",
          },
        },
        {
          id: 3,
          episodeId: "cky1gooc70064n0xqkt915h6r",
          guestId: "cky1gonti0028n0xqml7gmfcd",
          guest: {
            id: "cky1gonti0028n0xqml7gmfcd",
            name: "Davide Imola",
            email: "davide.imola@icloud.com",
            github: "davideimola",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "davideimola",
            linkedin: "davideimola",
            createdAt: "2022-01-05T11:32:51.990Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "cky1gop6f0107n0xqnbr4tf2n",
      title: "Setup progetto con Next.js, Github, k8s, etc.",
      description:
        "Iniziamo a costruire Space Hackability usando Next.js, GitHub e k8s con Ludovico, Davide e Lorenzo!",
      body: "\nDa dove iniziamo? Space Hackability è un progetto ambizioso e abbiamo poco tempo per svilupparlo.\nQuindi si parte alla grande! In questo primo vorremmo creare il progetto in [next.js](https://nextjs.org/),\naprire la repo GitHub, dockerizzare il server e fare un primo\ndeploy su #Kubernello!\n\n## Cosa abbiamo fatto?\n\n- Repo progetto -> https://github.com/hackability-dev/space.hackability\n- Setup progetto con [nextjs](https://nextjs.org/)\n- Connessione al DB tramite [Prisma](https://www.prisma.io/)\n- Immagine Docker creata -> [hackabilitydev/space-hackability](https://hub.docker.com/repository/docker/hackabilitydev/space-hackability)\n- Deploy su [Kubernello](https://github.com/livefun-dev/kubernello)\n- Sito preview live -> [space.k8s.hackability.dev/](https://space.k8s.hackability.dev/)\n\n![Demo](./demo.png)\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "eJAeXHk5CPw",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:53.751Z",
      updatedAt: "2022-01-05T11:32:53.752Z",
      scheduledTime: "2021-02-13T14:00:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 9,
          episodeId: "cky1gop6f0107n0xqnbr4tf2n",
          guestId: "cky1gonau0014n0xq0e1k3am7",
          guest: {
            id: "cky1gonau0014n0xq0e1k3am7",
            name: "Lorenzo Gallucci",
            email: "lgallucci@gmail.com",
            github: "log2",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "log_two",
            linkedin: "log2",
            createdAt: "2022-01-05T11:32:51.318Z",
            updatedAt: "2022-01-12T12:35:24.188Z",
          },
        },
        {
          id: 8,
          episodeId: "cky1gop6f0107n0xqnbr4tf2n",
          guestId: "cky1gonti0028n0xqml7gmfcd",
          guest: {
            id: "cky1gonti0028n0xqml7gmfcd",
            name: "Davide Imola",
            email: "davide.imola@icloud.com",
            github: "davideimola",
            bio: "DevOps Engineer",
            avatar: null,
            twitter: "davideimola",
            linkedin: "davideimola",
            createdAt: "2022-01-05T11:32:51.990Z",
            updatedAt: "2022-01-12T12:35:24.189Z",
          },
        },
      ],
    },
    {
      id: "cky1goq4t0186n0xqes7vto5k",
      title: "Kick-off hacakbility.dev",
      description:
        "Presentiamo il progetto hackability.dev insieme a Carlo, Ludovico e Chiara!",
      body: "\n**hackability.dev** è un progetto di Hackability che riunisce programmatore, makers, esperti\ne appassionati del settore dello sviluppo software per autare a creare in modalità\naperta una repository per condividere progetti Open Source sviluppati nel mondo della\ndisabilità da Hackability e chiunque voglia dare una mano.\n\nIn questo primo evento, Carlo, Ludovico e Chiara raccontano in che modo è nato il progetto\ne cosa si aspettano!\n",
      resources: null,
      image: null,
      hostId: "ckxyt46r5006609mk5ol04yyw",
      youtube: "2TiVLYdgF_c",
      twitch: "ludusrusso",
      category: "hackability.dev",
      createdAt: "2022-01-05T11:32:54.989Z",
      updatedAt: "2022-01-05T11:32:54.989Z",
      scheduledTime: "2021-01-28T17:30:00.000Z",
      host: {
        id: "ckxyt46r5006609mk5ol04yyw",
        name: "Ludovico Russo",
        email: "ludovico@ludusrusso.space",
        github: "ludusrusso",
        bio: "🚀 Fullstack developer",
        avatar: null,
        twitter: "ludusrusso",
        linkedin: "ludusrusso",
        createdAt: "2022-01-03T14:57:33.233Z",
        updatedAt: "2022-01-03T14:57:33.234Z",
      },
      guests: [
        {
          id: 18,
          episodeId: "cky1goq4t0186n0xqes7vto5k",
          guestId: "cky1gopyn0159n0xqihje74c8",
          guest: {
            id: "cky1gopyn0159n0xqihje74c8",
            name: "Chiara Bisignani",
            email: "chiara.bisignani@hackability.it",
            github: null,
            bio: "Arte, ICT e Communication",
            avatar:
              "https://res.cloudinary.com/ludusrusso/image/upload/c_crop,g_face/c_scale,w_200,h_200/v1641374825/ludusrusso.dev/participants/chiarabisi_wrzxdx.jpg",
            twitter: "KiabiCbisi",
            linkedin: "cbisi",
            createdAt: "2022-01-05T11:32:54.767Z",
            updatedAt: "2022-01-05T11:32:54.768Z",
          },
        },
        {
          id: 17,
          episodeId: "cky1goq4t0186n0xqes7vto5k",
          guestId: "cky1gopyo0161n0xqxta0g5r3",
          guest: {
            id: "cky1gopyo0161n0xqxta0g5r3",
            name: "Carlo Boccazzi Varotto",
            email: "carlo@hackability.it",
            github: null,
            bio: "Social Innovator",
            avatar:
              "https://res.cloudinary.com/ludusrusso/image/upload/c_crop,g_face/c_scale,w_200,h_200/v1641374825/ludusrusso.dev/participants/carlbv_shpwyt.jpg",
            twitter: null,
            linkedin: "carloboccazzivarotto",
            createdAt: "2022-01-05T11:32:54.768Z",
            updatedAt: "2022-01-05T11:32:54.769Z",
          },
        },
      ],
    },
  ].map((episode) => {
    return {
      ...episode,
      scheduledTime: new Date(episode.scheduledTime),
    };
  });
}
