import { glob } from "glob";
import { promises as fs } from "fs";
import matter from "gray-matter";
import path from "path";

interface Chapter {
  title: string;
  slug: string;
  content: string;
  published: boolean;
  description: string;
}

interface Course {
  title: string;
  description: string;
  author: string;
  toc: Chapter[];
  slug: string;
  content: string;
}

const getCourseData = async () => {
  const files = await getCoursesFiles();
  const datas = await Promise.all(files.map((f) => createCourseData(f)));
  return datas;
};

const createCourseData = async (file: string) => {
  const md = await fs.readFile(file);
  const { data, content } = matter(md) as unknown as {
    data: Course;
    content: string;
  };
  const readTime = readingTime(content);
  const slug = data.slug;

  const chaptersFiles = await getCourseChaptersFiles(file);
  const chapters = await Promise.all(
    chaptersFiles.map((f) => createCourseChapterData(f))
  );

  return {
    file,
    content,
    slug,
    frontMatter: {
      toc: chapters,
      author: data.author,
      title: data.title,
      readTime,
      href: path.join("/courses", slug),
      //   image: replacePath(file, data.image),
      imagePath: replacePath(file, "."),
      description: data.description,
    },
  };
};

const createCourseChapterData = async (file: string) => {
  const md = await fs.readFile(file);
  const { data, content } = matter(md) as unknown as {
    data: Chapter;
    content: string;
  };
  const readTime = readingTime(content);
  const slug = data.slug;

  return {
    file,
    content,
    slug,
    frontMatter: {
      title: data.title,
      readTime,
      // href: path.join("/courses", slug),
      //   image: replacePath(file, data.image),
      imagePath: replacePath(file, "."),
      description: data.description,
      published: data.published || false,
    },
  };
};

const replacePath = (file: string, p: string) => {
  return path.join(
    "/",
    file.replace(process.cwd() + "/courses", "/courses"),
    "..",
    p
  );
};

async function getCoursesFiles() {
  return new Promise<string[]>((resolve, reject) => {
    const contentDir = path.resolve(__dirname, "../courses");
    glob(contentDir + "/*/index.{md,mdx}", (err, files) => {
      if (err) {
        return reject(err);
      }
      resolve(files);
    });
  });
}

async function getCourseChaptersFiles(cpath: string) {
  return new Promise<string[]>((resolve, reject) => {
    const contentDir = path.resolve(cpath, "..");
    glob(contentDir + "/*/index.{md,mdx}", (err, files) => {
      if (err) {
        return reject(err);
      }
      resolve(files);
    });
  });
}

async function copyCoursesImages() {
  const src = path.resolve(__dirname, "../courses");
  const dst = path.resolve(__dirname, "../public/courses");
  try {
    await fs.rm(dst, { recursive: true });
  } catch {}
  await fs.mkdir(dst, { recursive: true });

  const imgs = await getFiles(src + "/**/*.{jpg,jpeg,png}");
  imgs.forEach(async (img) => {
    const imgDst = img.replace(src, dst);
    const fldDst = path.dirname(imgDst);
    try {
      await fs.mkdir(fldDst, { recursive: true });
    } catch {}
    await fs.copyFile(img, imgDst);
  });
}

const getFiles = (p: string) => {
  return new Promise<string[]>((resolve, reject) => {
    glob(p, (err, files) => {
      if (err) {
        return reject(err);
      }
      resolve(files);
    });
  });
};

function readingTime(text: string) {
  const wpm = 225;
  const words = text.trim().split(/\s+/).length;
  const time = Math.ceil(words / wpm);
  return time;
}

async function build() {
  const data = await getCourseData();
  await copyCoursesImages();

  await fs.writeFile(
    __dirname + "/../data/courses.ts",
    `// autogenerated by ${__filename}. Do not edit!

export type Course = typeof courses[number]
export type CourseChapter = Course["frontMatter"]["toc"][number]
export const getCourses = () => courses
export const getCourse = (slug: string) => courses.find(course => course.slug === slug)
export const getCourseChapter = (slug: string, cslug: string) =>
  courses
    .find((course) => course.slug === slug)
    ?.frontMatter.toc.find((chapter) => chapter.slug === cslug);

const courses = ${JSON.stringify(data, null, 2)}`
  );
}

build();
